### ISSUE TITLE
Cannot perform runtime binding on a null reference.

### ISSUE THREAD

**Issue by WatercolorGames** [RogueAI42/whoa#1]
This exception is thrown when attempting to serialize an object with a property with value `null`.

A workaround would be to populate the null property (in user code) with a default value, however in some cases this is impossible.

Another workaround in the library could be to read the value of the property using Reflection and if the returned `object` is null, write a special "null" byte (possibly 0x00) to the binary output.

Then when reading, before attempting to deserialize the property, look for this null value and if you get it, populate the property with `null` and continue to the next one.

Note that numeric types cannot be null, and neither can structs, so you won't have to worry about that. After all 0x00 is really `0` when stored in an integer. Not sure about floating point types.

**Comment by RogueAI42** [comment]
Should be resolved by a357337
